// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ex03.Data;

#nullable disable

namespace ex03.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ex03.Models.Cajero", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomApels")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Codigo");

                    b.ToTable("Cajeros");
                });

            modelBuilder.Entity("ex03.Models.MaquinaRegistradora", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("MaquinasRegistradoras");
                });

            modelBuilder.Entity("ex03.Models.Producto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ex03.Models.Venta", b =>
                {
                    b.Property<int>("CajeroCodigo")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductoCodigo")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("MaquinaCodigo")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("CajeroCodigo", "ProductoCodigo", "MaquinaCodigo");

                    b.HasIndex("MaquinaCodigo");

                    b.HasIndex("ProductoCodigo");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ex03.Models.Venta", b =>
                {
                    b.HasOne("ex03.Models.Cajero", "Cajero")
                        .WithMany("Ventas")
                        .HasForeignKey("CajeroCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ex03.Models.MaquinaRegistradora", "Maquina")
                        .WithMany("Ventas")
                        .HasForeignKey("MaquinaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ex03.Models.Producto", "Producto")
                        .WithMany("Ventas")
                        .HasForeignKey("ProductoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cajero");

                    b.Navigation("Maquina");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ex03.Models.Cajero", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ex03.Models.MaquinaRegistradora", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ex03.Models.Producto", b =>
                {
                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
